#!/usr/bin/env python3
"""
Convertir face.h5 en format TensorFlow.js
"""
import os
import sys
import json

try:
    from tensorflow import keras
    import tensorflowjs as tfjs
except ImportError as e:
    print(f"❌ Erreur d'import: {e}")
    print("Installez les dépendances: pip install tensorflow tensorflowjs")
    sys.exit(1)

def convert_model():
    """Convertir le modèle Keras en TensorFlow.js"""
    
    # Chemins
    model_path = './face.h5'
    output_dir = './assets/models/tfjs_model'
    
    print(f"📦 Chargement du modèle: {model_path}")
    
    # Vérifier que le fichier existe
    if not os.path.exists(model_path):
        print(f"❌ Fichier non trouvé: {model_path}")
        return False
    
    try:
        # Charger le modèle Keras
        model = keras.models.load_model(model_path)
        print(f"✅ Modèle chargé")
        print(f"📊 Architecture:")
        model.summary()
        
        # Créer le répertoire de sortie
        os.makedirs(output_dir, exist_ok=True)
        print(f"📁 Répertoire de sortie: {output_dir}")
        
        # Convertir en TensorFlow.js
        print(f"🔄 Conversion en TensorFlow.js...")
        tfjs.converters.save_keras_model(model, output_dir)
        print(f"✅ Conversion terminée!")
        
        # Vérifier les fichiers créés
        files = os.listdir(output_dir)
        print(f"📄 Fichiers créés:")
        for f in files:
            size = os.path.getsize(os.path.join(output_dir, f))
            print(f"  - {f} ({size} bytes)")
        
        # Lire et afficher le model.json
        model_json_path = os.path.join(output_dir, 'model.json')
        if os.path.exists(model_json_path):
            with open(model_json_path, 'r') as f:
                model_info = json.load(f)
            print(f"\n📋 Model.json info:")
            print(f"  Format: {model_info.get('format')}")
            print(f"  Generated by: {model_info.get('generatedBy')}")
            if 'modelTopology' in model_info:
                print(f"  Topology: {model_info['modelTopology']['class_name']}")
        
        return True
        
    except Exception as e:
        print(f"❌ Erreur lors de la conversion: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == '__main__':
    success = convert_model()
    sys.exit(0 if success else 1)
