#!/usr/bin/env python3
"""
Helper Script - Déploiement du Modèle
Automatise la conversion et la vérification du modèle
"""

import os
import sys
import subprocess
import json
from pathlib import Path

def check_prerequisites():
    """Vérifie les prérequis installés"""
    print("🔍 Vérification des prérequis...\n")
    
    # Vérifier Python
    try:
        result = subprocess.run([sys.executable, '--version'], capture_output=True, text=True)
        print(f"✅ Python: {result.stdout.strip()}")
    except Exception as e:
        print(f"❌ Python: {e}")
        return False
    
    # Vérifier pip
    try:
        result = subprocess.run([sys.executable, '-m', 'pip', '--version'], capture_output=True, text=True)
        print(f"✅ pip: {result.stdout.strip()}")
    except Exception as e:
        print(f"❌ pip: {e}")
        return False
    
    # Vérifier TensorFlow
    try:
        result = subprocess.run([sys.executable, '-c', 'import tensorflow; print(tensorflow.__version__)'], 
                              capture_output=True, text=True)
        print(f"✅ TensorFlow: {result.stdout.strip()}")
    except Exception as e:
        print(f"⚠️  TensorFlow non installé. Installation requise.")
        return False
    
    print()
    return True

def install_requirements():
    """Installe les dépendances nécessaires"""
    print("📦 Installation des dépendances...\n")
    
    packages = ['tensorflow', 'tensorflowjs']
    
    for package in packages:
        print(f"   ⬇️  Installation de {package}...")
        try:
            subprocess.run(
                [sys.executable, '-m', 'pip', 'install', '--upgrade', package],
                check=True,
                capture_output=True
            )
            print(f"   ✅ {package} installé")
        except subprocess.CalledProcessError as e:
            print(f"   ❌ Erreur: {e}")
            return False
    
    print()
    return True

def verify_model_file(h5_path):
    """Vérifie que le fichier modèle existe"""
    if not os.path.exists(h5_path):
        print(f"❌ Erreur: Fichier {h5_path} introuvable")
        print(f"\n📁 Fichiers .h5 trouvés:")
        for file in Path('.').glob('*.h5'):
            print(f"   - {file}")
        return False
    
    file_size = os.path.getsize(h5_path) / (1024 * 1024)
    print(f"✅ Modèle trouvé: {h5_path} ({file_size:.2f} MB)")
    return True

def verify_output_dir(output_dir):
    """Crée et vérifie le répertoire de sortie"""
    os.makedirs(output_dir, exist_ok=True)
    print(f"✅ Répertoire de sortie: {output_dir}")
    return True

def convert_model(h5_path, output_dir):
    """Convertit le modèle .h5 en TensorFlow.js"""
    print(f"\n📦 Conversion du modèle...\n")
    print(f"   Input:  {h5_path}")
    print(f"   Output: {output_dir}\n")
    
    cmd = [
        sys.executable, '-m', 'tensorflowjs.converters.convert_tf_saved_model' 
        if h5_path.endswith('_saved_model') else 'tensorflowjs_converter',
        '--input_format', 'keras',
        h5_path,
        output_dir
    ]
    
    # Utiliser tensorflowjs_converter directement
    cmd = [
        'tensorflowjs_converter',
        '--input_format', 'keras',
        h5_path,
        output_dir
    ]
    
    print(f"⚙️  Exécution: {' '.join(cmd)}\n")
    
    try:
        result = subprocess.run(cmd, check=True, capture_output=False, text=True)
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ Erreur conversion: {e}")
        return False
    except FileNotFoundError:
        print(f"❌ tensorflowjs_converter non trouvé")
        print(f"   Installation: pip install tensorflowjs")
        return False

def verify_output_files(output_dir):
    """Vérifie les fichiers de sortie"""
    print(f"\n✅ Vérification des fichiers générés...\n")
    
    required_files = ['model.json', 'model.weights.bin']
    
    for file in required_files:
        file_path = os.path.join(output_dir, file)
        if os.path.exists(file_path):
            size = os.path.getsize(file_path) / (1024 * 1024)
            print(f"   ✅ {file} ({size:.2f} MB)")
        else:
            print(f"   ❌ {file} (NOT FOUND)")
            return False
    
    # Vérifier le contenu de model.json
    model_json_path = os.path.join(output_dir, 'model.json')
    try:
        with open(model_json_path, 'r') as f:
            model_config = json.load(f)
            print(f"\n📊 Informations du modèle:")
            print(f"   Format: {model_config.get('format', 'N/A')}")
            print(f"   Generated by: {model_config.get('generatedBy', 'N/A')}")
    except Exception as e:
        print(f"   ⚠️  Impossible de lire model.json: {e}")
    
    return True

def main():
    print("=" * 60)
    print("🚀 Helper - Déploiement du Modèle de Reconnaissance Faciale")
    print("=" * 60)
    print()
    
    # Paramètres
    h5_file = 'face_recognition_model.h5'
    output_dir = './assets/models'
    
    # Étape 1: Vérifier les prérequis
    if not check_prerequisites():
        print("⚠️  Certains prérequis manquent")
        print("\n📥 Installation automatique...\n")
        if not install_requirements():
            print("❌ Impossible d'installer les dépendances")
            sys.exit(1)
    
    # Étape 2: Vérifier le fichier modèle
    if not verify_model_file(h5_file):
        print("\n💡 Aide:")
        print("   1. Téléchargez le modèle depuis Google Colab")
        print("   2. Placez le fichier .h5 dans le répertoire racine")
        print("   3. Relancez ce script")
        sys.exit(1)
    
    # Étape 3: Préparer le répertoire de sortie
    if not verify_output_dir(output_dir):
        sys.exit(1)
    
    # Étape 4: Convertir le modèle
    if not convert_model(h5_file, output_dir):
        sys.exit(1)
    
    # Étape 5: Vérifier les fichiers générés
    if not verify_output_files(output_dir):
        sys.exit(1)
    
    print("\n" + "=" * 60)
    print("✅ Déploiement terminé avec succès!")
    print("=" * 60)
    print("\n📝 Prochaines étapes:")
    print("   1. Exécutez: npm install")
    print("   2. Exécutez: npm run android (ou ios/web)")
    print("   3. Testez la reconnaissance faciale dans l'application")
    print()

if __name__ == '__main__':
    main()
